[package]
name = "nextboot-boot"
version.workspace = true
edition.workspace = true

[dependencies]
uefi.workspace = true
uefi-services.workspace = true
log.workspace = true
nextboot-fs.workspace = true
nextboot-config.workspace = true
nextboot-image.workspace = true
nextboot-virtio.workspace = true
nextboot-menu.workspace = true
nextboot-linux.workspace = true
nextboot-windows.workspace = true
xz4rust.workspace = true
