[workspace]
resolver = "2"
members = [
    "crates/nextboot-boot",
    "crates/nextboot-config",
    "crates/nextboot-fs",
    "crates/nextboot-image",
    "crates/nextboot-virtio",
    "crates/nextboot-menu",
    "crates/nextboot-linux",
    "crates/nextboot-windows",
    "crates/nextboot-smoke-efi",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nextboot/nextboot"
authors = ["NextBoot Team"]

[workspace.dependencies]
# UEFI 核心
uefi = { version = "0.28", features = ["alloc", "global_allocator", "panic_handler"] }
uefi-services = "0.25"

# 日志
log = "0.4"

# GPT 分区表
gpt = "4.0"

# 工具库
bitflags = "2.4"
byteorder = { version = "1.5", default-features = false }
xz4rust = { version = "0.2.1", default-features = false, features = ["alloc", "bcj", "crc64", "delta"] }

# 内部 crate
nextboot-fs = { path = "crates/nextboot-fs" }
nextboot-config = { path = "crates/nextboot-config" }
nextboot-image = { path = "crates/nextboot-image" }
nextboot-virtio = { path = "crates/nextboot-virtio" }
nextboot-menu = { path = "crates/nextboot-menu" }
nextboot-linux = { path = "crates/nextboot-linux" }
nextboot-windows = { path = "crates/nextboot-windows" }

[patch.crates-io]
uefi = { path = "vendor/uefi-0.28.0-nextboot" }

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = "z"      # 优化大小
lto = true           # Link-time optimization
codegen-units = 1    # 更好的优化
panic = "abort"      # 减少 panic 处理代码
strip = true         # 移除符号
